name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: hs_maringa_bot
          extract-git-tag: true
