name: Release

on:
  push:
    tags:
      - "*"

jobs:
  push_docker_image:
    runs-on: ubuntu-latest
    name: Build and Publish Docker Image
    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: hs_maringa_bot
          extract-git-tag: true

  release_binary:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/camera_bot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
